name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  library:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - 11.5
          - 11.6_beta
          - 12_beta
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Build and run tests
      run: swift test
